// Generated by CoffeeScript 1.6.2
/*
    A THREE.js experiment 2014 by http://bobbyroe.com
    Upgraded with Interactive GUI (v2.0) and Robust Checkbox Sync by Antigravity
*/

(function() {
  var SCREEN_HEIGHT, SCREEN_WIDTH, animate, camera, clock, controls, init, noise_mat, onWindowResize, parent, render, renderer, scene, start, ctrls, gui;

  SCREEN_HEIGHT = window.innerHeight;
  SCREEN_WIDTH = window.innerWidth;
  clock = new THREE.Clock();
  start = Date.now();
  
  ctrls = {
    disp_intensity: 10.0,
    speed: 1.0,
    use_rainbow: true,
    color: "#00a6ff",
    auto_rotate: true
  };

  init = function() {
    var ball_geo, extractNormals, particles, shader_attrs, shader_uniforms;

    camera = new THREE.PerspectiveCamera(20, SCREEN_WIDTH / SCREEN_HEIGHT, 1, 50000);
    camera.position.set(100, 100, 100);
    scene = new THREE.Scene();
    parent = new THREE.Object3D();
    scene.add(parent);
    
    // WebGL Renderer with Antialias
    renderer = new THREE.WebGLRenderer({ antialias: true });
    renderer.setSize(SCREEN_WIDTH, SCREEN_HEIGHT);
    document.body.appendChild(renderer.domElement);

    // TrackballControls Setup
    controls = new THREE.TrackballControls(camera, renderer.domElement);
    controls.staticMoving = true;
    controls.dynamicDampingFactor = 0.3;

    // GUI Initialization
    gui = new dat.GUI();
    gui.add(ctrls, 'disp_intensity', 0, 50).name('Displacement');
    gui.add(ctrls, 'speed', 0, 5).name('Speed');
    
    // Add explicit onChange to ensure value sync
    gui.add(ctrls, 'use_rainbow').name('Rainbow Mode').onChange(function(val) {
        console.log("Rainbow Mode changed to: " + val);
        if (noise_mat) noise_mat.uniforms['useRainbow'].value = val ? 1.0 : 0.0;
    });

    gui.addColor(ctrls, 'color').name('Color').onChange(function(val) {
        if (noise_mat) noise_mat.uniforms['uColor'].value.set(val);
    });

    gui.add(ctrls, 'auto_rotate').name('Auto Rotation').onChange(function(val) {
        console.log("Auto Rotation changed to: " + val);
    });

    var gui_dom = gui.domElement;
    gui_dom.addEventListener('mousedown', function() { controls.enabled = false; }, false);
    window.addEventListener('mouseup', function() { controls.enabled = true; }, false);

    ball_geo = new THREE.IcosahedronGeometry(20, 6);

    extractNormals = function(geo) {
      var vertex_normals = [];
      for (var i = 0; i < geo.faces.length; i++) {
        var face = geo.faces[i];
        vertex_normals[face.a] = face.vertexNormal0 || face.vertexNormals[0];
        vertex_normals[face.b] = face.vertexNormal1 || face.vertexNormals[1];
        vertex_normals[face.c] = face.vertexNormal2 || face.vertexNormals[2];
      }
      return vertex_normals;
    };

    shader_uniforms = {
      time: { type: "f", value: 0.0 },
      disp: { type: 'f', value: 10.0 },
      uColor: { type: 'c', value: new THREE.Color(ctrls.color) },
      useRainbow: { type: 'f', value: ctrls.use_rainbow ? 1.0 : 0.0 },
      rainbowTime: { type: 'f', value: 0.0 }
    };

    shader_attrs = {
      vNormal: { type: 'v3', value: extractNormals(ball_geo) }
    };

    noise_mat = new THREE.ShaderMaterial({
      uniforms: shader_uniforms,
      attributes: shader_attrs,
      vertexShader: document.getElementById('vert').textContent,
      fragmentShader: document.getElementById('frag').textContent
    });

    particles = new THREE.ParticleSystem(ball_geo, noise_mat);
    parent.add(particles);

    window.addEventListener('resize', onWindowResize, false);
    animate();
  };

  onWindowResize = function() {
    SCREEN_WIDTH = window.innerWidth;
    SCREEN_HEIGHT = window.innerHeight;
    renderer.setSize(SCREEN_WIDTH, SCREEN_HEIGHT);
    camera.aspect = SCREEN_WIDTH / SCREEN_HEIGHT;
    camera.updateProjectionMatrix();
  };

  animate = function() {
    requestAnimationFrame(animate);
    render();
  };

  render = function() {
    var time_delta = (Date.now() - start) * 0.001 * ctrls.speed;
    
    // Explicit check for rotate logic
    if (ctrls.auto_rotate === true) {
        parent.rotation.y += 0.005;
        parent.rotation.x += 0.002;
    }

    if (noise_mat) {
        noise_mat.uniforms['time'].value = time_delta * 0.5;
        noise_mat.uniforms['disp'].value = ctrls.disp_intensity;
        noise_mat.uniforms['useRainbow'].value = ctrls.use_rainbow ? 1.0 : 0.0;
        noise_mat.uniforms['rainbowTime'].value = (Date.now() * 0.0005) % 1.0;
    }

    renderer.render(scene, camera);
    controls.update();
  };

  if (document.readyState === 'loading') {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
