// Generated by CoffeeScript 1.7.1

/*
    A THREE.js experiment 2014 by http://bobbyroe.com
    Upgraded with Multi-Material & Environment Selection by Antigravity (v2.0)
 */
(function() {
  var bouncelight, box_mat, box_mesh, camera, clicked, controls, counter, ctrls, d, getMesh, getPhongMat, getRefractoMat, gold_mat, silver_mat, ruby_mat, emerald_mat, rainbow_mat, gui, head_geo, hideInfoPanel, info_panel, init, loader, log, objects, panel, parent, preloadAssets, refracto_mat, renderFrame, renderer, rimlight, scene, shader, showInfoPanel, sunlight, texture_blurred_cube, texture_cube, texture_disturb_cube, toggleInfoPanel, w;
  w = window;
  scene = new THREE.Scene();
  camera = new THREE.PerspectiveCamera(60, w.innerWidth / w.innerHeight, 0.1, 25000);
  renderer = new THREE.WebGLRenderer({ antialias: true });
  log = console.log.bind(console);
  
  // TrackballControls Initializations
  controls = new THREE.TrackballControls(camera, renderer.domElement);
  controls.rotateSpeed = 1.0;
  controls.zoomSpeed = 1.2;
  controls.staticMoving = true;
  controls.dynamicDampingFactor = 0.3;

  counter = 0;
  ctrls = {
    use_turntable: true,
    material: 'Gold',
    environment: 'Checkers'
  };
  w.ctrls = ctrls;
  gui = new dat.GUI();
  gui.add(ctrls, 'use_turntable').name('Turntable');
  
  // Select material and environment
  var mat_selector = gui.add(ctrls, 'material', ['Gold', 'Silver', 'Ruby', 'Emerald', 'Glass', 'Rainbow']).name('Select Material');
  var env_selector = gui.add(ctrls, 'environment', ['Checkers', 'Blurred', 'Studio Light']).name('Select Wall');

  scene.fog = new THREE.FogExp2(0x00ccFF, 0.0001);
  renderer.setSize(w.innerWidth, w.innerHeight);
  info_panel = document.querySelector('#info');
  panel = renderer.domElement;
  panel.classList.add('panel');
  document.body.insertBefore(panel, info_panel);

  loader = new THREE.OBJLoader();
  head_geo = null;

  // Load all textures upfront
  var path = "../z_images/", format = '.png';
  var urls = [path + 'checkers' + format, path + 'checkers' + format, path + 'checkers' + format, path + 'checkers' + format, path + 'checkers' + format, path + 'checkers' + format];
  var burls = [path + 'checkers_blurred' + format, path + 'checkers_blurred' + format, path + 'checkers_blurred' + format, path + 'checkers_blurred' + format, path + 'checkers_blurred' + format, path + 'checkers_blurred' + format];
  
  var d_path = "images/", d_format = '.jpg';
  var durls = [d_path + 'disturb3a' + d_format, d_path + 'disturb3a' + d_format, d_path + 'disturb3a' + d_format, d_path + 'disturb3a' + d_format, d_path + 'disturb3a' + d_format, d_path + 'disturb3a' + d_format];

  texture_cube = THREE.ImageUtils.loadTextureCube(urls, THREE.CubeReflectionMapping);
  texture_blurred_cube = THREE.ImageUtils.loadTextureCube(burls, THREE.CubeReflectionMapping);
  texture_disturb_cube = THREE.ImageUtils.loadTextureCube(durls, THREE.CubeReflectionMapping);

  getRefractoMat = function(env) {
    return new THREE.MeshBasicMaterial({
      color: 0xFFFFFF,
      envMap: env,
      refractionRatio: 0.95,
      mapping: THREE.CubeRefractionMapping 
    });
  };

  getPhongMat = function(type, env) {
    var map_height = THREE.ImageUtils.loadTexture("images/bump.jpg");
    var options = {
      envMap: env,
      bumpMap: map_height,
      color: 0xFFFFFF,
      specular: 0xFFFFFF,
      shininess: 45,
      bumpScale: 1.5,
      shading: THREE.SmoothShading,
      reflectivity: 0.7
    };

    switch(type) {
      case 'Gold':    options.emissive = 0x664400; options.color = 0xAA8800; break;
      case 'Silver':  options.emissive = 0x333333; options.specular = 0xEEEEEE; options.reflectivity = 0.9; break;
      case 'Ruby':    options.emissive = 0x880000; options.color = 0xFF2222; break;
      case 'Emerald': options.emissive = 0x008800; options.color = 0x22FF22; break;
      case 'Rainbow': options.emissive = 0x222222; options.color = 0xFFFFFF; break;
    }
    return new THREE.MeshPhongMaterial(options);
  };

  // Pre-generate materials (will update them dynamically)
  gold_mat = getPhongMat('Gold', texture_cube);
  silver_mat = getPhongMat('Silver', texture_cube);
  ruby_mat = getPhongMat('Ruby', texture_cube);
  emerald_mat = getPhongMat('Emerald', texture_cube);
  rainbow_mat = getPhongMat('Rainbow', texture_cube);
  refracto_mat = getRefractoMat(texture_cube);

  parent = new THREE.Object3D();
  scene.add(parent);

  sunlight = new THREE.DirectionalLight(0xffffdd, 1.2);
  bouncelight = new THREE.DirectionalLight(0xddffff, 0.4);
  rimlight = new THREE.DirectionalLight(0xddffff, 1.5);
  sunlight.position.set(1, 1, 1);
  bouncelight.position.set(-1, -1, -1);
  rimlight.position.set(0, 0.5, -1);
  scene.add(rimlight);
  scene.add(sunlight);
  scene.add(bouncelight);

  objects = [];
  init = function() {
    if (objects.length < 1) {
      var mesh = new THREE.Mesh(head_geo, gold_mat);
      mesh.position.set(0, -1000, 0);
      mesh.scale.set(1000, 1000, 1000);
      parent.add(mesh);
      objects.push({ mesh: mesh });
    }
    shader = THREE.ShaderLib["cube"];
    shader.uniforms["tCube"].value = texture_cube;
    box_mat = new THREE.ShaderMaterial({
      fragmentShader: shader.fragmentShader,
      vertexShader: shader.vertexShader,
      uniforms: shader.uniforms,
      depthWrite: false, side: THREE.BackSide
    });
    box_mesh = new THREE.Mesh(new THREE.BoxGeometry(20000, 20000, 20000), box_mat);
    scene.add(box_mesh);
    renderFrame();
  };

  camera.position.set(-1200, 800, 2000);

  var updateAllMats = function() {
    var env;
    switch(ctrls.environment) {
      case 'Checkers': env = texture_cube; break;
      case 'Blurred':  env = texture_blurred_cube; break;
      case 'Studio Light': env = texture_disturb_cube; break;
    }
    // Update materials envMap
    [gold_mat, silver_mat, ruby_mat, emerald_mat, rainbow_mat, refracto_mat].forEach(function(m) {
      m.envMap = env;
      m.needsUpdate = true;
    });
    // Update skybox
    if (box_mesh) {
      box_mesh.material.uniforms["tCube"].value = env;
    }
  };

  mat_selector.onChange(function(val) {
    if (!objects[0]) return;
    switch(val) {
      case 'Gold': objects[0].mesh.material = gold_mat; break;
      case 'Silver': objects[0].mesh.material = silver_mat; break;
      case 'Ruby': objects[0].mesh.material = ruby_mat; break;
      case 'Emerald': objects[0].mesh.material = emerald_mat; break;
      case 'Glass': objects[0].mesh.material = refracto_mat; break;
      case 'Rainbow': objects[0].mesh.material = rainbow_mat; break;
    }
  });

  env_selector.onChange(updateAllMats);

  renderFrame = function() {
    requestAnimationFrame(renderFrame);
    if (ctrls.use_turntable === true) {
      counter += 0.004;
      parent.rotation.y = counter * -1;
    }
    if (ctrls.material === 'Rainbow') {
      rainbow_mat.emissive.setHSL((Date.now() * 0.0005) % 1.0, 0.6, 0.2);
    }
    controls.update();
    renderer.render(scene, camera);
  };

  loader.load('../z_objs/asaro_04a.obj', function(obj) {
    obj.traverse(function(child) {
      if (child instanceof THREE.Mesh && !head_geo) { head_geo = child.geometry; }
    });
    if (head_geo) init();
  });

  clicked = function(evt) {
    if (evt.target.id === 'nub') {
      if (info_panel.classList.contains('open')) {
        panel.classList.remove('scooched_right');
        info_panel.classList.remove('open');
      } else {
        panel.classList.add('scooched_right');
        info_panel.classList.add('open');
      }
    }
  };
  document.addEventListener('click', clicked);
})();
